### PR TITLE
is there any way I can touch you?

### PR DESCRIPTION
**Pull request by membphis**
@Zheng-Xu I do not find any good way to touch you. so I created this issue

### CODE REVIEW

**Comment by membphis** [comment]
my mail: membphis@gmail.com

**Comment by Zheng-Xu** [comment]
I stopped to work on LuaJIT in 2017. Most of the code has been merged into upstream. The test part is not, because Mike Paul prefer testing in a separated project.

Can you share what you like to do? So that maybe I can spend some time to do some maintenance and merge the code in upstream .

**Comment by membphis** [comment]
We found that the performance of LuaJIT under ARM64 is not very good (not as good as X86 optimization), and would like to meet with you to see if there is an opportunity to cooperate.

I am the PMC of Apache APISIX, it mainly base on Nginx + LuaJIT, this is very important for us.

**Comment by Zheng-Xu** [comment]
@membphis I've sent you a message via email.

**Comment by membphis** [comment]
I have got your email and reply to you

**Pull request closed without merging**
